//! .opfspack binary format: reader/writer ported from the TypeScript
//! reference implementation (packages/opfspack in thundoku-shelf).
//! Byte layout must stay interoperable with the Web implementation.
//!
//! Wire-format facts (verified against `src/format.ts`, `src/builder.ts`,
//! `src/reader.ts`, `src/auth/identity-key.ts`, and fixtures generated by
//! the TS implementation itself):
//!
//! - everything little-endian
//! - header: 64 bytes, magic `OPFS`, version 2, CRC-32 (IEEE) over bytes 0..60
//! - entries stored back-to-back after the header, each 8-byte aligned
//! - index: sorted by path (UTF-16 code unit order), each entry 8-byte
//!   aligned, index CRC-32 appended — **`index_size` includes the CRC**
//! - compression is RAW DEFLATE (fflate `deflateSync`; no zlib wrapper)
//! - identity binding: PBKDF2-SHA256(sub + salt, salt, 100k) -> HKDF-SHA256
//!   (salt = packId, info = "opfspack-entry-key") -> AES-256-GCM per entry

#![forbid(unsafe_code)]

mod builder;
mod crypto;

/// Derive the per-pack AES key for an identity-bound pack.
/// Wraps master_key (PBKDF2 100k) + pack_key (HKDF) so callers can cache
/// the result instead of re-deriving it for every page.
pub fn derived_pack_key(id: &Identity) -> [u8; 32] {
    let master = crypto::master_key(&id.sub);
    crypto::pack_key(&master, &id.pack_id)
}
mod format;
mod reader;

pub use builder::PackBuilder;
pub use reader::{PackFileReader, PackReader};

/// Magic bytes at offset 0 of every pack.
pub const MAGIC: [u8; 4] = [0x4f, 0x50, 0x46, 0x53];
/// Fixed header size in bytes.
pub const HEADER_SIZE: usize = 64;
/// The only supported pack version.
pub const FORMAT_VERSION: u32 = 2;

/// Pack-level flags stored in the header.
pub mod pack_flags {
    /// No flags set.
    pub const NONE: u32 = 0;
    /// The pack was built with global compression enabled.
    pub const COMPRESSED: u32 = 1 << 0;
    /// The pack was built with identity binding enabled.
    pub const ENCRYPTED: u32 = 1 << 1;
}

/// Entry-level flags stored in each index entry.
pub mod entry_flags {
    /// No flags set.
    pub const NONE: u32 = 0;
    /// Entry payload is raw-DEFLATE compressed.
    pub const COMPRESSED: u32 = 1 << 0;
    /// Entry payload is AES-256-GCM encrypted.
    pub const ENCRYPTED: u32 = 1 << 1;
    /// Entry requires a Google identity (`Identity`) to decrypt.
    pub const IDENTITY_BOUND: u32 = 1 << 2;
    /// LZ4 compression — never produced by the TS implementation; reading
    /// such an entry fails with [`PackError::UnsupportedLz4`].
    pub const LZ4: u32 = 1 << 3;
}

/// Parsed pack header (CRC already validated by [`PackReader::open`]).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackHeader {
    pub version: u32,
    pub flags: u32,
    pub index_offset: u64,
    pub index_size: u64,
    pub entry_count: u32,
    pub created_at: u64,
}

/// One index entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackEntry {
    pub path: String,
    pub mime_type: String,
    /// Offset of the stored payload inside the pack body.
    pub offset: u64,
    /// Original (uncompressed, decrypted) size in bytes.
    pub size: u64,
    /// Stored size in bytes (compressed / encrypted).
    pub compressed_size: u64,
    pub flags: u32,
    /// AES-GCM nonce; zero for non-encrypted entries.
    pub iv: [u8; 12],
}

/// Identity used to decrypt identity-bound packs. `sub` is the Google
/// account subject; `pack_id` is the pack's book id (salt for HKDF).
#[derive(Debug, Clone)]
pub struct Identity {
    pub sub: String,
    pub pack_id: String,
}

/// Errors produced by pack reading and writing.
#[derive(Debug, thiserror::Error)]
pub enum PackError {
    #[error("unsupported pack version: {0}")]
    Version(u32),
    #[error("corrupted pack: {0}")]
    Corrupted(String),
    #[error("lz4 compression not supported")]
    UnsupportedLz4,
    #[error("identity required for encrypted entry: {0}")]
    IdentityRequired(String),
    #[error("entry not found: {0}")]
    NotFound(String),
    #[error("invalid range: {0}")]
    InvalidRange(String),
    #[error("pack I/O error: {0}")]
    Io(String),
}

/// SHA-256(`"opfspack:v1:{sub}"`) as lowercase hex — matches
/// `deriveOwnerId` in the TS `auth/identity-key.ts`.
pub fn derive_owner_id(sub: &str) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(format!("opfspack:v1:{sub}").as_bytes());
    digest.iter().map(|b| format!("{b:02x}")).collect()
}
