//! Interop tests against fixtures generated by the TypeScript reference
//! implementation (packages/opfspack/gen-fixtures.ts, bun + fflate 0.8.2).
//!
//! Wire-format facts verified against the TS source:
//! - little-endian throughout, header 64B, CRC-32 (IEEE) over bytes 0..60
//! - entries stored back-to-back, 8-byte aligned, after the header
//! - index: pathLen u16 / path / mimeLen u16 / mime / offset u64 / size u64
//!   / compressedSize u64 / flags u32 / IV 12B, each entry 8-byte aligned,
//!   index CRC-32 (4B) appended, INCLUDED in index_size
//! - compression is RAW DEFLATE (fflate deflateSync; no zlib wrapper)

use opfspack::{
    Identity, PackBuilder, PackError, PackReader, derive_owner_id, entry_flags, pack_flags,
};

fn page_a() -> Vec<u8> {
    format!("THUNDOKU_PAGE_0001:{}", "abc".repeat(4000)).into_bytes()
}

fn page_b() -> Vec<u8> {
    format!("THUNDOKU_PAGE_0002:{}", "xyz".repeat(2000)).into_bytes()
}

const META: &[u8] = br#"{"schemaVersion":1,"title":"Test Book","author":"Test Author"}"#;

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

fn load(name: &str) -> Vec<u8> {
    std::fs::read(format!("{FIXTURES}/{name}")).expect("fixture missing")
}

fn align8(n: u64) -> u64 {
    n.div_ceil(8) * 8
}

// ---- plain fixture -------------------------------------------------------
#[test]
fn plain_fixture_header_is_well_formed() {
    let bytes = load("plain.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    let header = reader.header();
    assert_eq!(header.version, 2);
    assert_eq!(header.entry_count, 3);
    assert_eq!(header.created_at, 1_728_000_000_000);
    // no compression flag on pack level? the fixture was built with
    // compress:true, so the pack flag is set
    assert_ne!(header.flags & pack_flags::COMPRESSED, 0);
    // layout: 64 + align8(62) + align8(56) + align8(6019)
    assert_eq!(
        header.index_offset,
        64 + align8(62) + align8(56) + align8(6019)
    );
    // index: 3 entries of 80B aligned + 4B CRC
    assert_eq!(header.index_size, 80 + 80 + 80 + 4);
}

#[test]
fn plain_fixture_entries_are_sorted_and_flagged() {
    let bytes = load("plain.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    let paths: Vec<&str> = reader.entries().iter().map(|e| e.path.as_str()).collect();
    assert_eq!(
        paths,
        vec![
            "metadata.json",
            "pages/page_0001.webp",
            "pages/page_0002.webp"
        ]
    );
    let meta = reader.entry("metadata.json").unwrap();
    assert_eq!(meta.mime_type, "application/json");
    assert_eq!(meta.size, 62);
    assert_eq!(meta.compressed_size, 62);
    assert_eq!(meta.flags, 0);
    let p1 = reader.entry("pages/page_0001.webp").unwrap();
    assert_eq!(p1.mime_type, "image/webp");
    assert_eq!(p1.size, page_a().len() as u64);
    assert_ne!(p1.flags & entry_flags::COMPRESSED, 0);
    assert_ne!(p1.compressed_size, p1.size);
    let p2 = reader.entry("pages/page_0002.webp").unwrap();
    assert_eq!(p2.flags, 0);
    assert_eq!(p2.compressed_size, p2.size);
    assert!(reader.entry("nope.txt").is_none());
}

#[test]
fn plain_fixture_reads_entry_bytes() {
    let bytes = load("plain.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    assert_eq!(reader.read_entry("metadata.json", None).unwrap(), META);
    assert_eq!(
        reader.read_entry("pages/page_0001.webp", None).unwrap(),
        page_a()
    );
    assert_eq!(
        reader.read_entry("pages/page_0002.webp", None).unwrap(),
        page_b()
    );
}

#[test]
fn plain_fixture_range_reads() {
    let bytes = load("plain.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    let full = page_a();
    let range = reader
        .read_entry_range("pages/page_0001.webp", 100, 200, None)
        .unwrap();
    assert_eq!(range, &full[100..200]);
    // invalid ranges
    assert!(matches!(
        reader.read_entry_range("pages/page_0001.webp", 10, 10, None),
        Err(PackError::InvalidRange(_))
    ));
    assert!(matches!(
        reader.read_entry_range("pages/page_0001.webp", 10, 9, None),
        Err(PackError::InvalidRange(_))
    ));
    assert!(matches!(
        reader.read_entry_range("pages/page_0001.webp", 0, (page_a().len() + 1) as u64, None),
        Err(PackError::InvalidRange(_))
    ));
}

// ---- identity-bound fixture ----------------------------------------------

#[test]
fn identity_fixture_requires_identity() {
    let bytes = load("identity-bound.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    assert_ne!(reader.header().flags & pack_flags::ENCRYPTED, 0);
    let err = reader.read_entry("pages/page_0001.webp", None).unwrap_err();
    assert!(matches!(err, PackError::IdentityRequired(ref p) if p == "pages/page_0001.webp"));
}

#[test]
fn identity_fixture_decrypts_with_correct_identity() {
    let bytes = load("identity-bound.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    let id = Identity {
        sub: "test-sub".into(),
        pack_id: "test-pack".into(),
    };
    assert_eq!(
        reader
            .read_entry("pages/page_0001.webp", Some(&id))
            .unwrap(),
        page_a()
    );
    assert_eq!(
        reader
            .read_entry("pages/page_0002.webp", Some(&id))
            .unwrap(),
        page_b()
    );
    assert_eq!(reader.read_entry("metadata.json", Some(&id)).unwrap(), META);
    // all entries flagged
    for e in reader.entries() {
        assert_ne!(e.flags & entry_flags::ENCRYPTED, 0);
        assert_ne!(e.flags & entry_flags::IDENTITY_BOUND, 0);
    }
}

#[test]
fn identity_fixture_wrong_identity_is_corrupted() {
    let bytes = load("identity-bound.opfspack");
    let reader = PackReader::open(&bytes).unwrap();
    let wrong = Identity {
        sub: "other-sub".into(),
        pack_id: "test-pack".into(),
    };
    assert!(matches!(
        reader.read_entry("pages/page_0001.webp", Some(&wrong)),
        Err(PackError::Corrupted(_))
    ));
    let wrong_pack = Identity {
        sub: "test-sub".into(),
        pack_id: "other-pack".into(),
    };
    assert!(matches!(
        reader.read_entry("pages/page_0001.webp", Some(&wrong_pack)),
        Err(PackError::Corrupted(_))
    ));
}

// ---- corruption and version rejection -------------------------------------

fn crc32(bytes: &[u8]) -> u32 {
    crc32fast::hash(bytes)
}

#[test]
fn rejects_truncated_and_bad_magic() {
    let bytes = load("plain.opfspack");
    assert!(matches!(
        PackReader::open(&bytes[..63]),
        Err(PackError::Corrupted(_))
    ));
    let mut bad = bytes.clone();
    bad[0] = b'X';
    assert!(matches!(
        PackReader::open(&bad),
        Err(PackError::Corrupted(_))
    ));
}

#[test]
fn rejects_header_crc_mismatch() {
    let mut bad = load("plain.opfspack");
    bad[8] ^= 0xff; // flags field
    assert!(matches!(
        PackReader::open(&bad),
        Err(PackError::Corrupted(_))
    ));
}

#[test]
fn rejects_version_3_with_corrected_crc() {
    let mut bytes = load("plain.opfspack");
    bytes[4..8].copy_from_slice(&3u32.to_le_bytes());
    let crc = crc32(&bytes[..60]);
    bytes[60..64].copy_from_slice(&crc.to_le_bytes());
    assert!(matches!(
        PackReader::open(&bytes),
        Err(PackError::Version(3))
    ));
}

#[test]
fn rejects_index_crc_mismatch() {
    let mut bytes = load("plain.opfspack");
    let index_offset = u64::from_le_bytes(bytes[16..24].try_into().unwrap()) as usize;
    bytes[index_offset] ^= 0x01; // first path byte
    assert!(matches!(
        PackReader::open(&bytes),
        Err(PackError::Corrupted(_))
    ));
}

#[test]
fn rejects_entry_pointing_beyond_body() {
    let mut bytes = load("plain.opfspack");
    // patch first entry offset to past the index start, fix index CRC
    let index_offset = u64::from_le_bytes(bytes[16..24].try_into().unwrap()) as usize;
    let index_size = u64::from_le_bytes(bytes[24..32].try_into().unwrap()) as usize;
    let first_entry = index_offset + 2 + "metadata.json".len() + 2 + "application/json".len();
    let off_pos = first_entry;
    bytes[off_pos..off_pos + 8].copy_from_slice(&(u64::MAX - 7).to_le_bytes());
    let crc = crc32(&bytes[index_offset..index_offset + index_size - 4]);
    bytes[index_offset + index_size - 4..index_offset + index_size]
        .copy_from_slice(&crc.to_le_bytes());
    assert!(matches!(
        PackReader::open(&bytes),
        Err(PackError::Corrupted(_))
    ));
}

#[test]
fn rejects_lz4_flag_with_corrected_crc() {
    let mut bytes = load("plain.opfspack");
    let index_offset = u64::from_le_bytes(bytes[16..24].try_into().unwrap()) as usize;
    let index_size = u64::from_le_bytes(bytes[24..32].try_into().unwrap()) as usize;
    // first entry is metadata.json: flags at 2+14+2+16+24
    let flags_pos = index_offset + 2 + "metadata.json".len() + 2 + "application/json".len() + 24;
    let flags = u32::from_le_bytes(bytes[flags_pos..flags_pos + 4].try_into().unwrap());
    bytes[flags_pos..flags_pos + 4].copy_from_slice(&(flags | 1 << 3).to_le_bytes());
    let crc = crc32(&bytes[index_offset..index_offset + index_size - 4]);
    bytes[index_offset + index_size - 4..index_offset + index_size]
        .copy_from_slice(&crc.to_le_bytes());
    let reader = PackReader::open(&bytes).unwrap();
    assert!(matches!(
        reader.read_entry("metadata.json", None),
        Err(PackError::UnsupportedLz4)
    ));
}

// ---- builder round-trips ---------------------------------------------------

#[test]
fn builder_roundtrip_plain() {
    let mut builder = PackBuilder::new(1_700_000_000_000);
    builder.add_entry("pages/page_0002.webp", page_b(), "image/webp", false);
    builder.add_entry("pages/page_0001.webp", page_a(), "image/webp", true);
    builder.add_entry("metadata.json", META.to_vec(), "application/json", false);
    let bytes = builder.build(None, true).unwrap();
    let reader = PackReader::open(&bytes).unwrap();
    assert_eq!(reader.header().version, 2);
    assert_eq!(reader.header().created_at, 1_700_000_000_000);
    assert_eq!(
        reader.read_entry("pages/page_0001.webp", None).unwrap(),
        page_a()
    );
    assert_eq!(
        reader.read_entry("pages/page_0002.webp", None).unwrap(),
        page_b()
    );
    assert_eq!(reader.read_entry("metadata.json", None).unwrap(), META);
    assert_ne!(
        reader
            .entry("pages/page_0001.webp")
            .unwrap()
            .compressed_size,
        page_a().len() as u64
    );
}

#[test]
fn builder_roundtrip_identity_bound() {
    let id = Identity {
        sub: "test-sub".into(),
        pack_id: "test-pack".into(),
    };
    let mut builder = PackBuilder::new(1_700_000_000_000);
    builder.add_entry("pages/page_0001.webp", page_a(), "image/webp", true);
    builder.add_entry("metadata.json", META.to_vec(), "application/json", false);
    let bytes = builder.build(Some(&id), true).unwrap();
    let reader = PackReader::open(&bytes).unwrap();
    assert_ne!(reader.header().flags & pack_flags::ENCRYPTED, 0);
    // without identity: rejected
    assert!(matches!(
        reader.read_entry("pages/page_0001.webp", None),
        Err(PackError::IdentityRequired(_))
    ));
    // with identity: original bytes
    assert_eq!(
        reader
            .read_entry("pages/page_0001.webp", Some(&id))
            .unwrap(),
        page_a()
    );
    assert_eq!(reader.read_entry("metadata.json", Some(&id)).unwrap(), META);
    // encrypted size = plaintext + GCM tag
    let meta = reader.entry("metadata.json").unwrap();
    assert_eq!(meta.compressed_size, META.len() as u64 + 16);
    // Rust-built pack must be readable by the TS reader (checked manually in
    // Verification; here we assert the TS-compatible layout invariants)
    assert!(reader.read_entry("pages/page_0001.webp", None).is_err());
}

#[test]
fn builder_sorts_entries_by_path() {
    let mut builder = PackBuilder::new(0);
    builder.add_entry("z.txt", vec![1, 2, 3], "text/plain", false);
    builder.add_entry("a.txt", vec![4, 5], "text/plain", false);
    let bytes = builder.build(None, false).unwrap();
    let reader = PackReader::open(&bytes).unwrap();
    let paths: Vec<&str> = reader.entries().iter().map(|e| e.path.as_str()).collect();
    assert_eq!(paths, vec!["a.txt", "z.txt"]);
}

#[test]
fn builder_empty_pack_is_valid() {
    let bytes = PackBuilder::new(42).build(None, false).unwrap();
    let reader = PackReader::open(&bytes).unwrap();
    assert_eq!(reader.header().entry_count, 0);
    assert!(reader.entries().is_empty());
}

// ---- key derivation --------------------------------------------------------

#[test]
fn owner_id_matches_ts_reference() {
    assert_eq!(
        derive_owner_id("test-sub"),
        "6366bfc3b6ab37feaf2adb385aeaa515c4aa52cf09e70cac890d888e4409f3b0"
    );
}
